name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}

      - name: GitHub Action for SwiftLint (Different working directory)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source

  build:
    name: build

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build

  test:
    name: test

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Test
        run: xcodebuild test -project CalculatorApp.xcodeproj/ -scheme CalculatorApp -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"

      - uses: kishikawakatsumi/xcresulttool@v1.3.0
        with:
          path: TestResults.xcresult
        if: success() || failure()
